### ISSUE TITLE
setting up VM-Image

### ISSUE THREAD

**Issue by gries** [wenjoseph/TCPDoS#1]
Hi,

I'm trying to setup a VM-Ware that runs this example.
I'm running ubuntu 12.10 server edition with:

I installed mininet via. _apt-get install mininet_ and added the termcolor module via. _pip install termcolor_.

But when I run ./run.sh I get the following output:

```
ubuntu-dev:~/tcp_dos/TCPDoS$ ./run.sh
Generate HTTP Test Files
--------------------------------------------------------------------------------
Caught exception.  Cleaning up...
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "tcp_dos.py", line 383, in main
    topo = NetworkTopo(switch_bw=args.bw_net, host_bw=args.bw_host, switch_delay='%sms' %(args.delay, ), queue_size=23593)
  File "tcp_dos.py", line 146, in __init__
    self.create_topology()
  File "tcp_dos.py", line 149, in create_topology
    hGoodSender = self.addHost('hGS')
AttributeError: 'NetworkTopo' object has no attribute 'addHost'
/usr/bin/iperf: no process found
Traceback (most recent call last):
  File "./util/plot-http.py", line 56, in <module>
    main()
  File "./util/plot-http.py", line 53, in main
    graph(args)
  File "./util/plot-http.py", line 24, in graph
    f = open("%s/http-data.txt" % (args.dir, ))
IOError: [Errno 2] No such file or directory: 'ddos-Apr22-23:04/http/http-data.txt'

```

**Comment by wenjoseph** [comment]
Hi,

Which mininet version are you using? is it 2.0.0?
It would be easier if you can use the EC2 image directly.

**Comment by gries** [comment]
I know that It would be easier to use the EC2 Image, but I really would like to setup the VM-Image myself without being dependent on amazon's services, I will gladly share the steps I had to do to get this running when I'm done, so any help will be appreciated :)

http://packages.ubuntu.com/quantal/mininet looks like installed version is: 2.0.0~d4-0ubuntu1 do I need another version?
